function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("#", "load_example")
end


function on_message(self, message_id, message, sender)
	print(message_id)
	if message_id == hash("load_example") then
		msg.post("#collectionproxy", "async_load")
	elseif message_id == hash("unload_example") then
		msg.post("#collectionproxy", "unload")
	elseif message_id == hash("proxy_loaded") then
		msg.post(sender, "enable")
	end
end